# Generated by Django 4.0.5 on 2022-08-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='hora',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='fecha',
        ),
    ]
